name: Continuous Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  deploy:
    name: Run Terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::326535729404:role/github-oidc-permissions-elbaz-Role-DCV4LZ6IXG79
          aws-region: eu-west-1

      - name: Run terraform
        run: |
          terraform init
          terraform workspace select elbaz
          terraform apply -var="github_api_token=${{ github.token }} " -var="route53_zone_id=Z00817091582026MN9AUQ" -var="domain_name=elbaz.env0-reg.opentf.org" -auto-approve