name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:
          aws-region: eu-west-1

      - name: Run terraform
        run: |
          terraform init
          terraform workspace select dev
          terraform apply -auto-approve
